version: '3.8'

services:
  db:
    image: mysql:8.0.11
    container_name: mysql8
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: kodesalon
      MYSQL_USER: kodesalon
      MYSQL_PASSWORD: kodesalon2021!
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  session:
    image: redis
    container_name: redis_session
    ports:
      - 6379:6379
  cache:
    image: redis
    container_name: redis_cache
    ports:
      - 6380:6379
    volumes:
      - ./docker/redis.conf:/usr/local/etc/redis/redis.conf
