spring:
  profiles:
    active: local
---

spring:
  group:
    prod:
      - prod-db

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:test_mem
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    database-platform: H2
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 50
        query:
          in_clause_parameter_padding: true
        format_sql: true
    open-in-view: false
