spring:
  profiles:
    active: local

---

spring:
  group:
    prod:
      - prod-db

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:test_mem
    driver-class-name: org.h2.Driver
    username: sa
    password:
