spring:
  profiles:
    active: local
---

spring:
  profiles:
    group:
      test: common
---

spring:
  profiles:
    group:
      local: common
---

spring:
  profiles:
    group:
      prod: common
---

spring:
  config:
    activate:
      on-profile: common
  datasource:
    hikari:
      auto-commit: false
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 50
        query:
          in_clause_parameter_padding: true
        format_sql: true
    open-in-view: false
---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/kodesalon?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: kodesalon
    password: kodesalon2021!
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  jwt:
    secret: bG9jYWxUZXN0S2V5
    accessExpirationMs: 180000
    refreshExpirationWeeks: 2
  flyway:
    locations: classpath:db/migration/local/{vendor}

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:test_mem;MODE=Mysql;DATABASE_TO_LOWER=TRUE;
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  jwt:
    secret: bG9jYWxUZXN0S2V5
    accessExpirationMs: 180000
    refreshExpirationWeeks: 2
  flyway:
    enabled: false
