spring:
  profiles:
    active: local
---

spring:
  profiles:
    group:
      local: common
---

spring:
  profiles:
    group:
      prod: common

---
spring:
  profiles:
    group:
      test: common, local
---

spring:
  config:
    activate:
      on-profile: common
  datasource:
    hikari:
      auto-commit: false
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 50
        query:
          in_clause_parameter_padding: true
        format_sql: true
    open-in-view: false
---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://db:3306/kodesalon?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: kodesalon
    password: kodesalon2021!
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  jwt:
    secret: bG9jYWxUZXN0S2V5
    accessExpirationMs: 1800000
    refreshExpirationWeeks: 2
  flyway:
    locations: classpath:db/migration/{vendor}
---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:mysql://db:3306/kodesalon?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false
    hikari:
      auto-commit: true


