spring:
  profiles:
    active: "local"
---
spring:
  config:
    activate:
      on-profile: "local"
  datasource:
    url: jdbc:h2:mem:test_mem
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    database-platform: H2
    hibernate:
      ddl-auto: create

